# the time in seconds of inactivity before the player is marked as afk
# use '-1' to disable this feature
afk-timeout-seconds: 120

# prevent afk players from moving
freeze-afk-players: true

# cancel afk status if the player jumps
# ONLY WORKS IF 'freeze-afk-players' IS TRUE
cancel-afk-on-jump: true

# cancel afk status if player moves more than 3 blocks
# else use the '/afk' command
# ONLY WORKS IF 'freeze-afk-players' IS FALSE
cancel-afk-on-move: true

# the player cannot take damage when he is afk
invulnerable-during-afk: true
