name: ${pluginName}
version: ${version}
main: de.codecrafter.smartAfk.AFKOG
api-version: ${apiVersion}
authors: [ Felix_Heidisch, NotAlexNoyle ]
website: https://github.com/true-og/AFK-OG
softdepend: [PlaceholderAPI]
commands:
  afk:
    description: Toggles the afk state.
    usage: /afk
