name: ${pluginName}
version: ${version}
main: de.codecrafter.smartAfk.SmartAfk
api-version: ${apiVersion}
authors: [ Felix Heidisch ]
website: https://github.com/IschdeFelin
softdepend: [PlaceholderAPI]
commands:
  afk:
    description: Toggles the afk state.
    usage: /afk
